//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hospital.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Transfer
    {
        public int pkID { get; set; }
        public int fkPID { get; set; }
        public int fkVisitID { get; set; }
        public int amount { get; set; }
        public string traking { get; set; }
        public string transid { get; set; }
        public string CardNumber { get; set; }
    
        public virtual tbl_Visit tbl_Visit { get; set; }
    }
}
